import json
import logging
from typing import Dict, Any, List, Optional
from app.services.ai_service import invoke_ai_summary, get_ai_provider
from app.services.dashboard_service import (
    get_executive_summary,
    get_facility_comparison,
    get_claims_intelligence,
    get_billing_intelligence,
    get_patient_ops_intelligence,
    get_doctor_staff_intelligence,
    get_laboratory_intelligence,
    get_pharmacy_inventory_intelligence,
    get_supply_chain_vendors,
    get_quality_compliance,
    get_financial_intelligence,
    get_ai_predictive_intelligence,
    get_workflow_automation
)

logger = logging.getLogger(__name__)

FACILITY_NAMES = {
    'all': 'All Network Facilities',
    'FAC001': 'Metro Health Center (FAC001)',
    'FAC002': 'St. Jude Community Hospital (FAC002)',
    'FAC003': 'Highland Regional Medical Center (FAC003)',
    'FAC004': 'Valley Childrens & Specialty Clinic (FAC004)',
    'FAC005': 'Lakeside Memorial Hospital (FAC005)'
}


def is_conversational_query(query: str) -> bool:
    """
    Identifies pure conversational messages, greetings, politeness, and capability queries.
    Prevents unnecessary Athena/S3 data queries when the user is simply greeting or asking for help.
    """
    q = query.strip().lower()
    q_clean = "".join(c for c in q if c.isalnum() or c.isspace()).strip()

    exact_greetings = {
        'hi', 'hello', 'hey', 'good morning', 'good afternoon', 'good evening',
        'greetings', 'howdy', 'yo', 'sup', 'help', 'hi there', 'hello there',
        'hey there', 'welcome'
    }
    if q_clean in exact_greetings:
        return True

    conversational_phrases = [
        'what can you do',
        'how can you help',
        'who are you',
        'what are your capabilities',
        'what do you do',
        'how does this work',
        'what is medops',
        'tell me about yourself',
        'thank you',
        'thanks',
        'can you help me',
        'help me'
    ]
    return any(p in q_clean for p in conversational_phrases)


def process_copilot_query(user_query: str, facility_id: str = 'all') -> Dict[str, Any]:
    """
    Processes natural-language operational healthcare queries.
    Uses Google Gemini as the PRIMARY language model to generate natural-language responses.
    For operational queries, verified metrics are retrieved from backend services and provided
    to Gemini as strict evidence so that Gemini never hallucinates numerical values.
    For conversational queries (greetings, help, capabilities), Gemini generates natural responses
    without querying operational tables.
    """
    q_lower = user_query.lower()
    facility_label = FACILITY_NAMES.get(facility_id, f"Facility {facility_id}")

    # =========================================================================
    # 1. PURE CONVERSATIONAL INTENT (GREETINGS, HELP, CAPABILITIES)
    # =========================================================================
    if is_conversational_query(user_query):
        source = "MedOps AI Assistant"
        domain = "Conversational Assistant"
        evidence: List[Dict[str, Any]] = []
        method = "Conversational natural-language response generated by Google Gemini"
        
        fallback_template = (
            f"Hello! I am your MedOps Operations AI Assistant for {facility_label}. "
            f"I can assist you with hospital operations analytics, including patient admissions, "
            f"bed occupancy, emergency wait times, claim denial rates, billing revenue, "
            f"pharmacy inventory, and clinical staff workload. How can I help you today?"
        )
        
        prompt = (
            f"You are the Medical Operations Intelligence AI Assistant (MedOps) for {facility_label}.\n"
            f"You assist hospital leadership, department directors, and operational staff by providing insights on "
            f"hospital operations, inpatient admissions, bed occupancy, emergency department throughput, "
            f"pharmacy inventory, insurance claim denials, billing revenue, and doctor/staff workload.\n\n"
            f"User message: {user_query}\n\n"
            f"Instructions:\n"
            f"- Answer naturally, warmly, professionally, and concisely.\n"
            f"- If the user greeted you, greet them warmly, state who you are, and ask how you can assist with hospital operations today.\n"
            f"- If the user asked what you can do or how you can help, summarize your key capabilities in hospital operations intelligence.\n"
            f"- Do NOT output an unprompted operational metrics report.\n"
            f"- Do NOT provide medical diagnosis, individual clinical advice, or treatment prescriptions."
        )

    # =========================================================================
    # 2. OPERATIONAL DOMAIN ROUTING & VERIFIED METRIC RETRIEVAL
    # =========================================================================
    # DOMAIN: Pharmacy / Inventory
    elif any(k in q_lower for k in ['medicine', 'reorder', 'inventory', 'stock', 'pharmacy', 'depletion', 'drug']):
        pharm = get_pharmacy_inventory_intelligence(facility_id)
        source = pharm.get('source', 'Local Dataset')
        tot_items = pharm.get('totalItems', 0)
        low_stock = pharm.get('lowStockCount', 0)
        out_stock = pharm.get('outOfStockCount', 0)
        low_items = pharm.get('lowStockItems', [])
        
        low_items_str = ", ".join([f"{item['medicine']} ({item['currentStock']} left vs {item['reorderLevel']} min)" for item in low_items[:3]])
        
        fallback_template = (
            f"Across {facility_label}, there are {low_stock} medicines currently below their reorder threshold "
            f"out of {tot_items:,} total inventory items monitored. {out_stock} items are completely out of stock. "
            f"Critical items needing immediate replenishment include: {low_items_str}."
        )
        domain = "Pharmacy & Inventory Operations"
        evidence = [
            {"metric": "Medicines Below Reorder Level", "value": f"{low_stock} items", "detail": "current_stock <= reorder_level"},
            {"metric": "Critical Stockouts (0 Units)", "value": f"{out_stock} items", "detail": "current_stock == 0"},
            {"metric": "Total Catalog Monitored", "value": f"{tot_items:,} items", "detail": "Core inventory database"}
        ]
        method = "Calculated from inventory.csv and medicines.csv by evaluating current_stock against reorder_level."
        verified_data = {
            "total_items_monitored": tot_items,
            "medicines_below_reorder_level": low_stock,
            "critical_stockouts_zero_units": out_stock,
            "top_reorder_items": low_items[:5]
        }
        prompt = (
            f"You are the Medical Operations Intelligence AI Assistant for {facility_label}.\n"
            f"Answer the user's operational healthcare question based STRICTLY on the following verified metrics and evidence.\n"
            f"Do NOT invent or hallucinate numbers.\n\n"
            f"Domain: {domain}\n"
            f"Verified Metrics:\n{json.dumps(verified_data, indent=2, default=str)}\n"
            f"Evidence:\n{json.dumps(evidence, indent=2, default=str)}\n\n"
            f"User Question: {user_query}\n\n"
            f"Provide a direct, natural-language explanation and actionable takeaway for hospital pharmacy managers. Do NOT give medical prescriptions or clinical treatment advice."
        )

    # DOMAIN: Claims & Denial Intelligence
    elif any(k in q_lower for k in ['denial', 'denied', 'claim', 'rejection', 'payer']):
        claims = get_claims_intelligence(facility_id)
        source = claims.get('source', 'Local Dataset')
        tot_claims = claims.get('totalClaims', 0)
        denied_claims = claims.get('deniedClaims', 0)
        denial_rate = claims.get('denialRate', 0.0)
        denied_amt = claims.get('deniedAmount', 0.0)
        reasons = claims.get('denialReasons', [])
        top_reason_str = ", ".join([f"'{r['reason']}' ({r['count']} claims)" for r in reasons[:3]]) if reasons else "N/A"

        fallback_template = (
            f"For {facility_label}, the verified Claim Denial Rate is {denial_rate}%. "
            f"Out of {tot_claims:,} total submitted insurance claims, {denied_claims:,} claims were denied, "
            f"representing ₹{denied_amt:,.2f} in exposed hospital revenue. "
            f"The top drivers of claim denial are: {top_reason_str}."
        )
        domain = "Insurance Claims Intelligence"
        evidence = [
            {"metric": "Claim Denial Rate", "value": f"{denial_rate}%", "detail": "denied / total claims"},
            {"metric": "Total Denied Claims", "value": f"{denied_claims:,} claims", "detail": f"Out of {tot_claims:,} total"},
            {"metric": "Denied Revenue Exposure", "value": f"₹{denied_amt:,.2f}", "detail": "Sum of claimed_amount for denied status"},
            {"metric": "Primary Denial Reason", "value": reasons[0]['reason'] if reasons else "None", "detail": f"{reasons[0]['count']} claims" if reasons else "N/A"}
        ]
        method = "Aggregated from claims.csv by filtering claim_status == 'Denied' and computing percentage of total submissions."
        verified_data = {
            "claim_denial_rate_pct": denial_rate,
            "total_claims_submitted": tot_claims,
            "denied_claims_count": denied_claims,
            "denied_revenue_exposure_inr": denied_amt,
            "top_denial_reasons": reasons[:5]
        }
        prompt = (
            f"You are the Medical Operations Intelligence AI Assistant for {facility_label}.\n"
            f"Answer the user's operational healthcare question based STRICTLY on the following verified metrics and evidence.\n"
            f"Do NOT invent or hallucinate numbers.\n\n"
            f"Domain: {domain}\n"
            f"Verified Metrics:\n{json.dumps(verified_data, indent=2, default=str)}\n"
            f"Evidence:\n{json.dumps(evidence, indent=2, default=str)}\n\n"
            f"User Question: {user_query}\n\n"
            f"Provide a direct, natural-language explanation and strategic takeaway for hospital revenue cycle management."
        )

    # DOMAIN: Bed Occupancy & Inpatient Capacity
    elif any(k in q_lower for k in ['bed', 'occupancy', 'census']):
        exec_sum = get_executive_summary(facility_id)
        p_ops = get_patient_ops_intelligence(facility_id)
        source = exec_sum.get('source', 'Local Dataset')
        raw = exec_sum.get('rawMetrics', {})

        occupancy_rate = raw.get('occupancyRate', 0.0)
        tot_adm = raw.get('totalAdmissions', 0)
        avg_los = raw.get('avgLOS', 0.0)

        fallback_template = (
            f"Bed Capacity & Inpatient Census for {facility_label}: Current bed occupancy stands at {occupancy_rate}%. "
            f"Total cumulative admissions reach {tot_adm:,} patients with an average Length of Stay (ALOS) of {avg_los} days."
        )
        domain = "Inpatient Capacity & Bed Management"
        evidence = [
            {"metric": "Bed Occupancy Rate", "value": f"{occupancy_rate}%", "detail": "Active inpatient census ratio"},
            {"metric": "Total Inpatient Admissions", "value": f"{tot_adm:,} patients", "detail": "From admissions.csv"},
            {"metric": "Average Length of Stay", "value": f"{avg_los} days", "detail": "Discharge date - admission date"}
        ]
        method = "Calculated from beds.csv and admissions.csv evaluating occupied beds against total capacity."
        verified_data = {
            "bed_occupancy_rate_pct": occupancy_rate,
            "total_inpatient_admissions": tot_adm,
            "average_length_of_stay_days": avg_los
        }
        prompt = (
            f"You are the Medical Operations Intelligence AI Assistant for {facility_label}.\n"
            f"Answer the user's operational healthcare question based STRICTLY on the following verified metrics and evidence.\n"
            f"Do NOT invent or hallucinate numbers.\n\n"
            f"Domain: {domain}\n"
            f"Verified Metrics:\n{json.dumps(verified_data, indent=2, default=str)}\n"
            f"Evidence:\n{json.dumps(evidence, indent=2, default=str)}\n\n"
            f"User Question: {user_query}\n\n"
            f"Provide a direct, natural-language operational explanation and strategic takeaway for inpatient capacity management."
        )

    # DOMAIN: Patient Operations & Admissions & Emergency
    elif any(k in q_lower for k in ['patient', 'admission', 'admitted', 'admit', 'inpatient', 'emergency', 'ed visit', 'ed wait', 'waiting time', 'length of stay', 'los', 'triage']):
        p_ops = get_patient_ops_intelligence(facility_id)
        source = p_ops.get('source', 'Local Dataset')
        
        tot_adm = p_ops.get('totalAdmissions', 0)
        avg_los = p_ops.get('avgLengthOfStay', 0.0)
        ed_count = p_ops.get('emergencyVisits', 0)
        avg_ed_wait = p_ops.get('avgEDWaitTime', 0.0)

        fallback_template = (
            f"Patient Operations for {facility_label}: Inpatient admissions total {tot_adm:,} with an average "
            f"Length of Stay (LOS) of {avg_los} days. Emergency department encounters stand at {ed_count:,} "
            f"with an average ED waiting time of {avg_ed_wait} minutes."
        )
        domain = "Patient Operations & Clinical Flow"
        evidence = [
            {"metric": "Inpatient Admissions", "value": f"{tot_adm:,} admissions", "detail": "From admissions.csv"},
            {"metric": "Average Length of Stay", "value": f"{avg_los} days", "detail": "Discharge date - admission date"},
            {"metric": "Emergency Department Visits", "value": f"{ed_count:,} visits", "detail": "From emergency_visits.csv"},
            {"metric": "Average ED Waiting Time", "value": f"{avg_ed_wait} minutes", "detail": "Triage to physician examination"}
        ]
        method = "Aggregated from admissions.csv and emergency_visits.csv."
        verified_data = {
            "total_admissions": tot_adm,
            "average_length_of_stay_days": avg_los,
            "emergency_visits": ed_count,
            "average_ed_wait_minutes": avg_ed_wait
        }
        prompt = (
            f"You are the Medical Operations Intelligence AI Assistant for {facility_label}.\n"
            f"Answer the user's operational healthcare question based STRICTLY on the following verified metrics and evidence.\n"
            f"Do NOT invent or hallucinate numbers.\n\n"
            f"Domain: {domain}\n"
            f"Verified Metrics:\n{json.dumps(verified_data, indent=2, default=str)}\n"
            f"Evidence:\n{json.dumps(evidence, indent=2, default=str)}\n\n"
            f"User Question: {user_query}\n\n"
            f"Provide a direct, natural-language explanation and strategic takeaway for hospital clinical flow and operations."
        )

    # DOMAIN: Billing & Financial Revenue
    elif any(k in q_lower for k in ['revenue', 'billed', 'billing', 'accounts receivable', ' ar ', 'collection', 'financial', 'p&l', 'profit', 'expenses']):
        billing = get_billing_intelligence(facility_id)
        source = billing.get('source', 'Local Dataset')
        
        gross_rev = billing.get('grossRevenue', 0.0)
        net_collected = billing.get('totalRevenue', 0.0)
        outstanding_ar = billing.get('outstandingAR', 0.0)
        col_rate = round((net_collected / gross_rev * 100), 1) if gross_rev > 0 else 0.0

        fallback_template = (
            f"Financial Intelligence for {facility_label}: Gross billed revenue is ₹{gross_rev:,.2f} (₹{gross_rev/1e6:.2f}M), "
            f"with net realized collections of ₹{net_collected:,.2f} (₹{net_collected/1e6:.2f}M), yielding an overall realization rate of {col_rate}%. "
            f"Outstanding Accounts Receivable (A/R) currently stands at ₹{outstanding_ar:,.2f} (₹{outstanding_ar/1e6:.2f}M)."
        )
        domain = "Billing & Revenue Intelligence"
        evidence = [
            {"metric": "Net Realized Revenue", "value": f"₹{net_collected/1e6:.2f}M", "detail": f"Exact: ₹{net_collected:,.2f}"},
            {"metric": "Gross Billed Revenue", "value": f"₹{gross_rev/1e6:.2f}M", "detail": f"Exact: ₹{gross_rev:,.2f}"},
            {"metric": "Outstanding A/R", "value": f"₹{outstanding_ar/1e6:.2f}M", "detail": f"Exact: ₹{outstanding_ar:,.2f}"},
            {"metric": "Revenue Realization Rate", "value": f"{col_rate}%", "detail": "net / gross billed"}
        ]
        method = "Calculated from billing.csv by summing gross_amount, paid_amount, and unpaid balances."
        verified_data = {
            "gross_billed_revenue_inr": gross_rev,
            "net_collected_revenue_inr": net_collected,
            "outstanding_ar_inr": outstanding_ar,
            "realization_rate_pct": col_rate
        }
        prompt = (
            f"You are the Medical Operations Intelligence AI Assistant for {facility_label}.\n"
            f"Answer the user's operational healthcare question based STRICTLY on the following verified metrics and evidence.\n"
            f"Do NOT invent or hallucinate numbers.\n\n"
            f"Domain: {domain}\n"
            f"Verified Metrics:\n{json.dumps(verified_data, indent=2, default=str)}\n"
            f"Evidence:\n{json.dumps(evidence, indent=2, default=str)}\n\n"
            f"User Question: {user_query}\n\n"
            f"Provide a direct, natural-language explanation and strategic takeaway for healthcare financial leadership."
        )

    # DOMAIN: Supply Chain & Vendors
    elif any(k in q_lower for k in ['supplier', 'vendor', 'purchase order', ' po ', 'po value', 'procurement', 'scar', 'lead time']):
        sc = get_supply_chain_vendors(facility_id)
        source = sc.get('source', 'Local Dataset')
        kpis = sc.get('kpis', {})
        vendors = sc.get('vendors', [])
        
        tot_vendors = kpis.get('totalVendors', len(vendors))
        high_risk_vendors = [v for v in vendors if v.get('riskLevel') == 'High']
        high_risk_cnt = len(high_risk_vendors)
        avg_quality = kpis.get('avgQualityScore', 0.0)
        avg_on_time = kpis.get('avgOnTimeDeliveryPct', 0.0)
        tot_po_val = kpis.get('totalPOValue', 0.0)

        high_risk_names = ", ".join([v['name'] for v in high_risk_vendors[:3]]) if high_risk_vendors else "None"

        fallback_template = (
            f"Supply Chain assessment for {facility_label}: There are {high_risk_cnt} high-risk suppliers identified "
            f"out of {tot_vendors} contracted vendors. The overall average supplier quality score is {avg_quality}/100 with an "
            f"average on-time delivery rate of {avg_on_time}%. Active purchase orders represent a total value of ₹{tot_po_val:,.2f}. "
            f"Vendors operating with elevated risk flags include: {high_risk_names}."
        )
        domain = "Supply Chain & Vendor Management"
        evidence = [
            {"metric": "High-Risk Suppliers", "value": f"{high_risk_cnt} vendors", "detail": f"Out of {tot_vendors} vendors"},
            {"metric": "Average Quality Score", "value": f"{avg_quality} / 100", "detail": "Quality audit inspection score"},
            {"metric": "Average On-Time Delivery", "value": f"{avg_on_time}%", "detail": "Fulfillment SLA adherence"},
            {"metric": "Total Active PO Value", "value": f"₹{tot_po_val/1e6:.2f}M", "detail": f"Exact: ₹{tot_po_val:,.2f}"}
        ]
        method = "Aggregated from vendor_performance.csv, purchase_orders.csv, and supply_chain_purchase_orders.csv."
        verified_data = {
            "total_vendors": tot_vendors,
            "high_risk_vendors_count": high_risk_cnt,
            "average_quality_score": avg_quality,
            "average_on_time_delivery_pct": avg_on_time,
            "total_po_value_inr": tot_po_val,
            "high_risk_vendor_examples": [v['name'] for v in high_risk_vendors[:3]]
        }
        prompt = (
            f"You are the Medical Operations Intelligence AI Assistant for {facility_label}.\n"
            f"Answer the user's operational healthcare question based STRICTLY on the following verified metrics and evidence.\n"
            f"Do NOT invent or hallucinate numbers.\n\n"
            f"Domain: {domain}\n"
            f"Verified Metrics:\n{json.dumps(verified_data, indent=2, default=str)}\n"
            f"Evidence:\n{json.dumps(evidence, indent=2, default=str)}\n\n"
            f"User Question: {user_query}\n\n"
            f"Provide a direct, natural-language explanation and strategic takeaway for hospital procurement and supply chain management."
        )

    # DOMAIN: Quality, Compliance & CAPA
    elif any(k in q_lower for k in ['quality', 'incident', 'capa', 'corrective action', 'compliance', 'audit', 'hipaa', 'infection', 'complaint']):
        qc = get_quality_compliance(facility_id)
        source = qc.get('source', 'Local Dataset')
        kpis = qc.get('kpis', {})
        
        tot_incidents = kpis.get('totalIncidents', 0)
        sev_counts = kpis.get('incidentsBySeverity', {})
        crit_cnt = sev_counts.get('Critical', 0)
        high_cnt = sev_counts.get('High', 0)
        active_capa = kpis.get('activeCAPACount', 0)
        tot_capa = kpis.get('totalCAPACount', 0)
        comp_score = kpis.get('overallComplianceScore', 0.0)

        fallback_template = (
            f"Quality & Regulatory status for {facility_label}: A total of {tot_incidents:,} quality incidents are logged, "
            f"with {crit_cnt} Critical and {high_cnt} High severity events requiring mandatory clinical governance review. "
            f"There are {active_capa} active Corrective and Preventive Actions (CAPA) currently in progress (out of {tot_capa} total). "
            f"The enterprise audit compliance score stands at {comp_score}%."
        )
        domain = "Quality & Regulatory Compliance"
        evidence = [
            {"metric": "Total Incidents Logged", "value": f"{tot_incidents:,}", "detail": "From quality_incidents.csv"},
            {"metric": "Critical Severity Incidents", "value": f"{crit_cnt} events", "detail": "Immediate clinical escalation"},
            {"metric": "Active CAPA Actions", "value": f"{active_capa} active", "detail": f"Out of {tot_capa} total CAPAs"},
            {"metric": "Enterprise Compliance Score", "value": f"{comp_score}%", "detail": "Audit compliance index"}
        ]
        method = "Aggregated from quality_incidents.csv, quality_audits.csv, and corrective_actions.csv."
        verified_data = {
            "total_incidents": tot_incidents,
            "critical_severity_incidents": crit_cnt,
            "high_severity_incidents": high_cnt,
            "active_capas": active_capa,
            "total_capas": tot_capa,
            "overall_compliance_score": comp_score
        }
        prompt = (
            f"You are the Medical Operations Intelligence AI Assistant for {facility_label}.\n"
            f"Answer the user's operational healthcare question based STRICTLY on the following verified metrics and evidence.\n"
            f"Do NOT invent or hallucinate numbers.\n\n"
            f"Domain: {domain}\n"
            f"Verified Metrics:\n{json.dumps(verified_data, indent=2, default=str)}\n"
            f"Evidence:\n{json.dumps(evidence, indent=2, default=str)}\n\n"
            f"User Question: {user_query}\n\n"
            f"Provide a direct, natural-language explanation and strategic takeaway for healthcare quality and clinical governance leadership."
        )

    # DOMAIN: Doctor & Staff Workload
    elif any(k in q_lower for k in ['doctor', 'physician', 'staff', 'nurse', 'workload', 'utilization', 'overtime', 'working hours']):
        staff = get_doctor_staff_intelligence(facility_id)
        source = staff.get('source', 'Local Dataset')
        
        avg_util = staff.get('avgDoctorUtilization', 0.0)
        tot_hrs = staff.get('totalWorkingHours', 0.0)
        ot_hrs = staff.get('overtimeHours', 0.0)
        doc_cnt = staff.get('activeDoctorsCount', 0)
        ot_pct = round((ot_hrs / tot_hrs * 100), 1) if tot_hrs > 0 else 0.0

        fallback_template = (
            f"Doctor & Staff Operations for {facility_label}: Active physician roster comprises {doc_cnt} doctors "
            f"operating at an average clinical utilization rate of {avg_util}%. "
            f"Total logged workload spans {tot_hrs:,.1f} working hours, including {ot_hrs:,.1f} overtime hours ({ot_pct}% overtime load)."
        )
        domain = "Doctor & Clinical Staff Intelligence"
        evidence = [
            {"metric": "Active Doctors", "value": f"{doc_cnt} physicians", "detail": "Roster headcount"},
            {"metric": "Average Doctor Utilization", "value": f"{avg_util}%", "detail": "Clinical hours vs scheduled shift"},
            {"metric": "Total Working Hours", "value": f"{tot_hrs:,.1f} hrs", "detail": "Aggregated clinical hours"},
            {"metric": "Overtime Hours", "value": f"{ot_hrs:,.1f} hrs", "detail": f"{ot_pct}% of total shift hours"}
        ]
        method = "Computed from doctor_workload.csv and doctors.csv."
        verified_data = {
            "active_doctors_count": doc_cnt,
            "average_doctor_utilization_pct": avg_util,
            "total_working_hours": tot_hrs,
            "overtime_hours": ot_hrs,
            "overtime_ratio_pct": ot_pct
        }
        prompt = (
            f"You are the Medical Operations Intelligence AI Assistant for {facility_label}.\n"
            f"Answer the user's operational healthcare question based STRICTLY on the following verified metrics and evidence.\n"
            f"Do NOT invent or hallucinate numbers.\n\n"
            f"Domain: {domain}\n"
            f"Verified Metrics:\n{json.dumps(verified_data, indent=2, default=str)}\n"
            f"Evidence:\n{json.dumps(evidence, indent=2, default=str)}\n\n"
            f"User Question: {user_query}\n\n"
            f"Provide a direct, natural-language explanation and strategic takeaway for medical staff administration."
        )

    # DOMAIN: Laboratory & Diagnostics
    elif any(k in q_lower for k in ['lab', 'test', 'diagnostic', 'turnaround', 'tat', 'specimen', 'pathology']):
        lab = get_laboratory_intelligence(facility_id)
        source = lab.get('source', 'Local Dataset')
        
        tot_orders = lab.get('totalOrders', 0)
        avg_tat = lab.get('avgTAT', 0.0)
        completed = lab.get('completedOrders', 0)
        cats = lab.get('categories', [])
        top_cat_str = ", ".join([f"{c['category']} ({c['orders']} orders, {c['avgTAT']}h TAT)" for c in cats[:3]]) if cats else "N/A"

        fallback_template = (
            f"Laboratory Operations for {facility_label}: {tot_orders:,} diagnostic orders are recorded, "
            f"with {completed:,} completed results. The average laboratory turnaround time (TAT) is {avg_tat} hours. "
            f"High-volume diagnostic disciplines include: {top_cat_str}."
        )
        domain = "Laboratory & Diagnostics Operations"
        evidence = [
            {"metric": "Total Diagnostic Orders", "value": f"{tot_orders:,}", "detail": "From lab_orders_results.csv"},
            {"metric": "Average Turnaround Time", "value": f"{avg_tat} hours", "detail": "order to result release"},
            {"metric": "Completed Results", "value": f"{completed:,}", "detail": "Result verified and finalized"},
            {"metric": "Top Discipline Volume", "value": cats[0]['category'] if cats else "N/A", "detail": f"{cats[0]['orders']} orders" if cats else "N/A"}
        ]
        method = "Aggregated from lab_orders_results.csv and lab_tests.csv."
        verified_data = {
            "total_diagnostic_orders": tot_orders,
            "average_turnaround_time_hours": avg_tat,
            "completed_results": completed,
            "categories": cats[:5]
        }
        prompt = (
            f"You are the Medical Operations Intelligence AI Assistant for {facility_label}.\n"
            f"Answer the user's operational healthcare question based STRICTLY on the following verified metrics and evidence.\n"
            f"Do NOT invent or hallucinate numbers.\n\n"
            f"Domain: {domain}\n"
            f"Verified Metrics:\n{json.dumps(verified_data, indent=2, default=str)}\n"
            f"Evidence:\n{json.dumps(evidence, indent=2, default=str)}\n\n"
            f"User Question: {user_query}\n\n"
            f"Provide a direct, natural-language explanation and strategic takeaway for diagnostic laboratory operations."
        )

    # DOMAIN: Predictive Intelligence, Bottlenecks & Forecasts
    elif any(k in q_lower for k in ['forecast', 'predict', 'projection', 'bottleneck', 'no-show', 'anomaly']):
        pred = get_ai_predictive_intelligence(facility_id)
        source = pred.get('source', 'Local Dataset')
        kpis = pred.get('kpis', {})
        
        f_vol = kpis.get('forecastVolume', 0)
        risk_score = kpis.get('riskScore', 0.0)
        bottleneck_count = kpis.get('bottlenecksCount', 0)
        ns_risk = kpis.get('noShowRiskPct', 12.1)
        denial_exp = kpis.get('denialRiskExposureFormatted', '₹500.9k')

        fallback_template = (
            f"Predictive Intelligence for {facility_label}: The 7-day encounter forecast projects {f_vol:,} patient visits "
            f"with an enterprise operational risk score of {risk_score}/100. There are {bottleneck_count} active workflow bottlenecks identified. "
            f"Patient no-show probability is modeled at {ns_risk}%, and claim denial financial exposure stands at {denial_exp}."
        )
        domain = "Predictive Intelligence & Forecasting"
        evidence = [
            {"metric": "7-Day Projected Encounters", "value": f"{f_vol:,} encounters", "detail": "Linear/polynomial trend regression"},
            {"metric": "Operational Risk Index", "value": f"{risk_score} / 100", "detail": "Multi-factor delay and capacity model"},
            {"metric": "Identified Bottlenecks", "value": f"{bottleneck_count} delays", "detail": "Transfer and discharge SLA breaches"},
            {"metric": "Projected Denial Exposure", "value": denial_exp, "detail": "High-risk pending claims"}
        ]
        method = "Generated via statistical time-series regression and historical operational variance models."
        verified_data = {
            "forecast_encounter_volume": f_vol,
            "operational_risk_score": risk_score,
            "bottlenecks_count": bottleneck_count,
            "no_show_risk_pct": ns_risk,
            "denial_risk_exposure": denial_exp
        }
        prompt = (
            f"You are the Medical Operations Intelligence AI Assistant for {facility_label}.\n"
            f"Answer the user's operational healthcare question based STRICTLY on the following verified metrics and evidence.\n"
            f"Do NOT invent or hallucinate numbers.\n\n"
            f"Domain: {domain}\n"
            f"Verified Metrics:\n{json.dumps(verified_data, indent=2, default=str)}\n"
            f"Evidence:\n{json.dumps(evidence, indent=2, default=str)}\n\n"
            f"User Question: {user_query}\n\n"
            f"Provide a direct, natural-language explanation and strategic takeaway for healthcare predictive planning."
        )

    # DOMAIN: Executive Summary / General Operations (Default)
    else:
        exec_sum = get_executive_summary(facility_id)
        source = exec_sum.get('source', 'Local Dataset')
        raw = exec_sum.get('rawMetrics', {})
        
        tot_adm = raw.get('totalAdmissions', 0)
        avg_los = raw.get('avgLOS', 0.0)
        tot_rev = raw.get('totalRevenue', 0.0)
        denial_rate = raw.get('denialRate', 0.0)
        avg_ed_wait = raw.get('avgEDWait', 0.0)
        occupancy_rate = raw.get('occupancyRate', 0.0)

        fallback_template = (
            f"Operational Summary for {facility_label}: Total patient admissions are {tot_adm:,} with an average "
            f"Length of Stay of {avg_los} days and bed occupancy at {occupancy_rate}%. Net realized revenue is ₹{tot_rev/1e6:.2f}M (₹{tot_rev:,.2f}). "
            f"Emergency department patients wait an average of {avg_ed_wait} minutes, and the overall claim denial rate is {denial_rate}%."
        )
        domain = "Executive Operations Command"
        evidence = [
            {"metric": "Total Patient Admissions", "value": f"{tot_adm:,}", "detail": "Verified admission records"},
            {"metric": "Net Realized Revenue", "value": f"₹{tot_rev/1e6:.2f}M", "detail": f"Exact: ₹{tot_rev:,.2f}"},
            {"metric": "Average ED Waiting Time", "value": f"{avg_ed_wait} mins", "detail": "Arrival to triage consultation"},
            {"metric": "Claim Denial Rate", "value": f"{denial_rate}%", "detail": "Denied claims ratio"},
            {"metric": "Bed Occupancy Rate", "value": f"{occupancy_rate}%", "detail": "Active inpatient census"}
        ]
        method = "Aggregated across admissions.csv, billing.csv, claims.csv, and emergency_visits.csv."
        verified_data = {
            "total_patient_admissions": tot_adm,
            "average_length_of_stay_days": avg_los,
            "net_realized_revenue_inr": tot_rev,
            "claim_denial_rate_pct": denial_rate,
            "average_ed_wait_minutes": avg_ed_wait,
            "bed_occupancy_rate_pct": occupancy_rate
        }
        prompt = (
            f"You are the Medical Operations Intelligence AI Assistant for {facility_label}.\n"
            f"Answer the user's operational healthcare administration question based STRICTLY on the following verified metrics and evidence.\n"
            f"Do NOT invent or hallucinate any numbers or statistics. Cite the relevant verified figures accurately.\n\n"
            f"Operational Domain: {domain}\n"
            f"Verified Operational Metrics:\n{json.dumps(verified_data, indent=2, default=str)}\n"
            f"Key Evidence:\n{json.dumps(evidence, indent=2, default=str)}\n\n"
            f"User Question: {user_query}\n\n"
            f"Provide a concise executive operational summary and strategic takeaway for hospital leadership. Do NOT give medical diagnosis or treatment advice."
        )

    # =========================================================================
    # 3. AI PROVIDER INVOCATION (GOOGLE GEMINI PRIMARY WITH HONEST FALLBACK)
    # =========================================================================
    ai_used = False
    provider_instance = get_ai_provider()
    active_provider_name = provider_instance.get_provider_name()
    model_used = getattr(provider_instance, 'model_id', 'gemini-3.1-flash-lite')
    provider_used = active_provider_name
    ai_explanation = ""
    ai_status = f"{active_provider_name}: Standby"
    answer = fallback_template

    try:
        ai_res = invoke_ai_summary(prompt)
        if ai_res.get('status') == 'success' and ai_res.get('summary'):
            ai_used = True
            answer = ai_res['summary']
            ai_explanation = ai_res['summary']
            model_used = ai_res.get('modelId', model_used)
            provider_used = ai_res.get('provider', active_provider_name)
            ai_status = f"{provider_used}: Active ({model_used})"
        else:
            err = ai_res.get('errorMessage') or 'Offline'
            provider_used = f"{active_provider_name} (Deterministic Fallback)"
            ai_status = f"{provider_used}: Standby ({err[:35]}...)"
            answer = fallback_template
            ai_explanation = (
                f"Deterministic Analytics Mode: Query resolved directly from verified {source} telemetry. "
                f"Calculations performed across operational records for {facility_label}. "
                f"AI foundation model is in standby ({err[:60]}) and metrics were verified deterministically."
            )
    except Exception as e:
        logger.warning(f"AI invocation error: {e}")
        provider_used = f"{active_provider_name} (Deterministic Fallback)"
        ai_status = f"{provider_used}: Error ({type(e).__name__})"
        answer = fallback_template
        ai_explanation = (
            f"Deterministic Analytics Mode: Query resolved directly from verified {source} telemetry. "
            f"Calculations performed across operational records for {facility_label}. "
            f"AI foundation model encountered an error and metrics were verified deterministically."
        )

    is_fallback = not ai_used

    return {
        "question": user_query,
        "query": user_query,
        "answer": answer,
        "data_source": source,
        "domain": domain,
        "evidence": evidence,
        "method": method,
        "bedrock_used": ai_used and active_provider_name == "Amazon Bedrock",
        "ai_used": ai_used,
        "ai_provider": provider_used,
        "model": model_used,
        "is_fallback": is_fallback,
        "ai_explanation": ai_explanation,
        "ai_status": ai_status,
        "facility_id": facility_id
    }
